// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUsdOvVsNlN5kQq9dcxc873tcC19opKrw',
    appId: '1:122190377224:web:967025043c43259493bcbd',
    messagingSenderId: '122190377224',
    projectId: 'smartstudy-8ec37',
    authDomain: 'smartstudy-8ec37.firebaseapp.com',
    storageBucket: 'smartstudy-8ec37.firebasestorage.app',
    measurementId: 'G-CDDPDSEYRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFzq7rcFvf_Bg_OXg2iVyFXgnVoFT9V_4',
    appId: '1:122190377224:android:8b20a2b5ca04cc7693bcbd',
    messagingSenderId: '122190377224',
    projectId: 'smartstudy-8ec37',
    storageBucket: 'smartstudy-8ec37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzgg-rWSTqyyV-WC6Zck7aMoSwgz2mRFQ',
    appId: '1:122190377224:ios:2de5ed28d4f2fb3693bcbd',
    messagingSenderId: '122190377224',
    projectId: 'smartstudy-8ec37',
    storageBucket: 'smartstudy-8ec37.firebasestorage.app',
    iosBundleId: 'com.example.codigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzgg-rWSTqyyV-WC6Zck7aMoSwgz2mRFQ',
    appId: '1:122190377224:ios:2de5ed28d4f2fb3693bcbd',
    messagingSenderId: '122190377224',
    projectId: 'smartstudy-8ec37',
    storageBucket: 'smartstudy-8ec37.firebasestorage.app',
    iosBundleId: 'com.example.codigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUsdOvVsNlN5kQq9dcxc873tcC19opKrw',
    appId: '1:122190377224:web:69f736139b78f3eb93bcbd',
    messagingSenderId: '122190377224',
    projectId: 'smartstudy-8ec37',
    authDomain: 'smartstudy-8ec37.firebaseapp.com',
    storageBucket: 'smartstudy-8ec37.firebasestorage.app',
    measurementId: 'G-W2RWBDHMNQ',
  );

}